<a href="https://colab.research.google.com/github/19PA1A02A8/AI-Lab/blob/master/Experiment_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment NO.1 : NUMPY

###1)Different ways to create a Numpy arrays

In [ ]:
import numpy as np
P = np.array([[5,6,7],[8,9,10]])
print (P)

[[ 5  6  7]
 [ 8  9 10]]


###2) Add,remove,modify array elements

###Add

In [ ]:
a=np.array([1,2,3])
b=np.append(a,[10,20,30])
print(b)

[ 1  2  3 10 20 30]


###Remove

In [8]:
c= np.delete(a,2)
print(c)

[3 4]


###Modify

In [10]:
c[c<5]=-1
print(c)

[-1 -1]


###3) Arthmetic operations on Numpy arrays

In [4]:
import numpy as np
a=([3,4,5])
b=([6,7,8])
num_sum = np.add(a,b)
num_diff = np.subtract(a,b)
num_quo = np.divide(a,b)
num_mod = np.mod(a,b)
num_pow = np.power(a,b)
print(num_sum)
print(num_diff)
print(num_quo)
print(num_mod)
print(num_pow)

[ 9 11 13]
[-3 -3 -3]
[0.5        0.57142857 0.625     ]
[3 4 5]
[   729  16384 390625]


###4) slicing and iterating of numpy arrays

###Slicing

In [5]:
import numpy as np
arr = np.array([3,4,5,6,7,8,9,10,11,12])
print(arr[5:11])

[ 8  9 10 11 12]


###Iterating

In [6]:
for X in arr:
 print(X)

3
4
5
6
7
8
9
10
11
12


###5) Matrix operations on Numpy arrays

In [1]:
import numpy as np
a = np.array([[3,4],[5,6]])
b = np.array([[7,8],[9,10]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[[10 12]
 [14 16]]
[[-4 -4]
 [-4 -4]]
[[0.42857143 0.5       ]
 [0.55555556 0.6       ]]
